#!/bin/bash

check () {
  if ! [ -d $1/.git ]; then
    echo "Failed to clone $1 module" >&2
    exit 1
  fi
}

cd `dirname $0`
mkdir modules
git clone https://github.com/ste78/puppet-alcesbase.git modules/alcesbase --branch symphony
check modules/alcesbase || exit 1
git clone https://github.com/ste78/puppet-alceshpc.git modules/alceshpc --branch symphony
check modules/alceshpc || exit 1
#git clone https://github.com/ste78/puppet-alcesmonitoring.git alcesmonitoring --branch symphony
#check alcesmonitoring || exit 1
#git clone https://github.com/ste78/puppet-alcesnetwork.git alcesnetwork --branch symphony
#check alcesnetwork || exit 1
git clone https://github.com/ste78/puppet-alcesservices.git modules/alcesservices --branch symphony
check modules/alcesservices || exit 1
git clone https://github.com/puppetlabs/puppetlabs-stdlib.git --branch 3.2.x modules/stdlib
check modules/stdlib || exit 1
git clone https://github.com/deanwilson/puppet-multitemplate.git modules/puppet-multitemplate
check modules/puppet-multitemplate || exit 1
git clone https://github.com/ste78/puppet-alcesconfigs.git hieradata --branch symphony
check hieradata || exit 1
mkdir manifests
ln -snf ../hieradata/site.pp manifests/site.pp
mv `basename $0` `basename $0`.done
